import 'package:flutter/material.dart';

const kMainColor = Color(0xFF243b67);
const kSecondaryColor = Color(0xFFffd897);
const KThirdColor = Color(0xFFb57304);
const kProductName = 'productName';
const kProductPrice = 'productPrice';
const kProductDescription = 'productDescription';
const kProductLocation = 'productLocation';
const kProductCategory = 'productCategory';
const kProductsCollection = 'Products';
const kUnActiveColor = Color(0xFFC1BDB8);
const kJackets = 'jackets';
const kTrousers = 'trousers';
const kTshirts = 't-shirts';
const kShoes = 'shoes';
const kOrders = 'Orders';
const kOrderDetails = 'OrderDetails';
const kTotallPrice = 'TotallPrice';
const kAddress = 'Address';
const kProductQuantity = 'Quantity';
const kKeepMeLoggedIn = 'KeepMeLoggedIn';
